var questions=[
"    only be able to speak whale or only understand whale",
"Be famous or work at the grain terminal forever",
"Eat a monkey's brain or drink human breast milk",
"Always be wearing sopping wet jeans or have to carry everything around in chip bags",
"Have to navigate places by setting “waypoints” and moving in a straight line to that waypoint. You can reset a waypoint every 10 minutes but you can’t deviate from the line because of obstacles. Or, you have to bear crawl ",
"Be Winnie or Stew",
"live in a minimum security prison or be alone in the woods",
"Eat an asshole or be an asshole",
"Leech or teach (information)",
"Have a lot of body hair or be bald",
"Have amazing sex once a year, or below average every day",
"Work with dead bodies or in the sewer system",
"Only get joy from pandering media (trashy love novels, reality TV, fan service anime) or drive a bus professionally until retirement",
"Always find hair in your food, or not be able to taste sweet things",
"Breathe under water or fly",
"Be unable to function without taking a huge number of supplements (Oh my zinc is low I’ll have to go home right away), or pee your pants a bit every time you laugh",
"Shit your pants every time you fly or only be able to exercise in the rain. ",
"Truly believe in god or know factually that there is a hell.",
"Travel to every country on the planet or know everyone in a town.",
"Have a draft in your house that you can never quite find the source or always have spiderwebs appearing that are just a bit out of reach.",
"Have chocolate or sex (classic question)",
"Be rich or famous",
"Never have the correct thing brought to you in a restaurant or not be able to tell the difference between the correct and the incorrect order.",
"Have your car break down once a month, or be sick for one month a year.",
"Find love or happiness.",
"Mind swap with your SO for gender bent sex or always eat cake for breakfast",
"Be able to turn into any animal and not be able to communicate with them, or be able to communicate with every animal (like doc doolittle) and not be the animal.",
"Every time you open a can the contents are random things from cans (sparking water -> tomato soup, Sardines -> coca cola), or not be able to read.",
" Be fast or strong",
"Have clairvoyant knowledge of every object you have directly touched with your skin (i.e you know where your mom is at all times and what she is doing, and every package you have ever sent), or you know the full history of every object that you touch.",
"Unlock any door, or unlock any heart",
"Give the best oral sex of anyone in history (stolen from oglaf), or be the greatest surgeon of all time.",
"Always need a fan on to get to sleep, or always need a cup of coffee in the morning (you ain’t getting to sleep without that fan, or out of it without the coffee)",
"No executive function, or no artistic drive and taste.",
"Always be able to light up a room, or be able to understand everyone in it.",
"Be able to fix anything around the house with whatever tools you have available or be able to dress well with whatever clothes you find around.",
"Sleep like the princess and the pea, or have OCD.",
"Be a man or a woman",
"Be good with kids or good with animals.",
"Have a calming touch and chilling words or calming words and chilling touch",
"Speak every language on earth or know yourself better than anyone has ever known themselves.",
"Be poor, or stupid.",
"No matter what you eat it always tastes like a root vegetable, or your shoes never quite fit right and you will get blisters eventually.",
"Diabetic or Diarrhretic",
"Die by getting murdered at the climax of a story for the ages or go peacefully at some random point in your sleep.",
"Get surprise dosed with 3 tabs of acid (when you are not in danger / a position of responsibility), get mugged (no permanent injury or death).",
"Only eat potatoes or be a couch potato",
"Every time you touch someone you see the worst experience of their life, or when you touch someone they see the worst in yours.",
"Get random but kinda powerful electric static shocks even when you should not really be getting them, like from touching a rubber duck, or always be fumbling things like a bar of soap",
"Technology always breaks when you try to use it, or you can never figure out how to use technology.",
"Never be able to cum from sex and only be able to cum from eating white Christmas pie, or every time you cum during sex, you get a white Christmas pie in your face and your partner gets a pumpkin pie in their face",
"Be stunningly beautiful or stinking rich",
"Be Joan of Arc or Cleopatra",
]

function new_question() {
    var random_number=Math.floor(Math.random()*(questions.length));
    document.getElementById("question").innerHTML=questions[random_number];

}